"""PostgreSQL ENUM-backed model field, with explicit migration operations.

``EnumField`` is a ``CharField`` wired to a :mod:`django_utils.choices`
``Choices`` class: ``choices``/``max_length`` are derived from it, and on
PostgreSQL the column's real type is a native ``CREATE TYPE ... AS ENUM``
type instead of ``VARCHAR`` -- the database itself then rejects a row
that doesn't hold one of the declared values, on top of (not instead of)
Django's own choice validation. On every other backend ``db_type()``
falls back to plain ``VARCHAR``, so a model using ``EnumField`` stays
portable -- SQLite never sees a Postgres-specific type name.

The field never issues DDL for the enum type itself -- that is the job
of three explicit ``migrations.Operation`` subclasses you add to a
migration BY HAND. Django's autodetector has no concept of "create this
standalone database object first", so these are never auto-generated by
``makemigrations``:

``CreateEnumType(name, values)``
    ``CREATE TYPE <name> AS ENUM (<values>)``. Add it to the same
    migration as -- and *before* -- the ``AddField``/``CreateModel``
    operation that introduces the ``EnumField`` column using it; the
    type must exist before a column can reference it.

``AddEnumValue(name, value)``
    ``ALTER TYPE <name> ADD VALUE IF NOT EXISTS <value>``. PostgreSQL
    cannot run this statement inside a transaction block on versions
    before 12, and even on 12+ a value added in one transaction can't be
    used in that same transaction. It sets ``atomic = False``, but that
    alone is NOT enough: Django's migration executor opens its schema
    editor -- and with it, the wrapping transaction -- keyed on the
    *Migration's* ``atomic`` attribute (default ``True``), before any
    operation's own ``atomic`` flag is ever consulted; the operation-level
    flag can only add extra wrapping inside that, never escape it. Put
    ``AddEnumValue`` in its own migration with ``atomic = False`` set as a
    CLASS attribute on that ``Migration`` (same convention as Django's own
    ``AddIndexConcurrently``). Skip that and ``database_forwards`` raises
    ``NotSupportedError`` instead of running -- it never applies the value
    from inside a transaction. It is also irreversible -- PostgreSQL has
    no ``DROP VALUE`` -- so reversing it raises ``IrreversibleError``. The
    recreate-and-migrate escape hatch (create a new type with the
    reduced value list, migrate the column and data across, drop the
    old type) is documented in the README.

``DropEnumType(name, values)``
    The reverse of ``CreateEnumType``. It takes the same ``values`` as
    ``CreateEnumType`` so that ITS OWN reversal (recreating the type)
    has something to recreate.

All three are DB-only: ``state_forwards`` is a no-op (there is no model
state for a standalone database type -- ``EnumField`` doesn't need one
either, its ``deconstruct()`` carries the ``Choices`` class, not the
type's existence) and ``database_forwards``/``database_backwards`` are
no-ops on every non-PostgreSQL vendor, so a migration using them still
applies cleanly against SQLite or MySQL -- just without the enum type's
extra database-level integrity check. SQL is always built with
``schema_editor.quote_name()`` for identifiers and
``schema_editor.quote_value()`` for values, never raw string
interpolation of unquoted input.
"""

import re
import typing
from typing import TYPE_CHECKING

from django.db import NotSupportedError, models
from django.db.migrations.exceptions import IrreversibleError
from django.db.migrations.operations.base import Operation

from django_utils import choices

if TYPE_CHECKING:
    from collections.abc import Sequence

    from django.db.backends.base.base import BaseDatabaseWrapper
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import ProjectState

_CAMEL_BOUNDARY = re.compile(r'(?<!^)(?=[A-Z])')


def _default_enum_type(choices_class: 'type[choices.Choices]') -> str:
    """``SandwichStatus`` -> ``'sandwich_status'``."""
    return _CAMEL_BOUNDARY.sub('_', choices_class.__name__).lower()


def _values(choices_class: 'type[choices.Choices]') -> list[typing.Any]:
    values = choices_class.choices.keys()
    if not values:
        raise ValueError(
            f'{choices_class.__name__} defines no choices; EnumField '
            f'needs at least one'
        )
    return values


def _max_length(choices_class: 'type[choices.Choices]') -> int:
    return max(len(str(value)) for value in _values(choices_class))


def _choice_pairs(
    choices_class: 'type[choices.Choices]',
) -> list[tuple[typing.Any, typing.Any]]:
    return [
        (value, choice.label)
        for value, choice in choices_class.choices.items()
    ]


if TYPE_CHECKING:
    # ``CharField`` is only ``Generic[_ST, _GT]`` in django-stubs, not at
    # runtime -- ``CharField[Any, Any]`` as an actual base class raises
    # ``TypeError: type 'CharField' is not subscriptable``.
    _FieldBase = models.CharField[typing.Any, typing.Any]
else:
    _FieldBase = models.CharField


class EnumField(_FieldBase):
    """``CharField`` whose ``choices``/``max_length`` come from a
    :class:`django_utils.choices.Choices` class, with a native PostgreSQL
    ENUM column type (plain ``VARCHAR`` on every other backend).

    ``choices`` is always derived from ``choices_class`` -- there is no
    override; passing a ``choices=`` keyword too raises ``TypeError``
    (``CharField.__init__`` got two values for it). ``max_length`` is
    derived as the longest value's length unless given explicitly.
    ``enum_type`` defaults to ``choices_class``'s name in snake_case
    (``SandwichStatus`` -> ``'sandwich_status'``) and names the
    PostgreSQL type this field's column references -- that type must
    already exist by the time this field's table/column is created; see
    ``CreateEnumType`` in the module docstring.
    """

    def __init__(
        self,
        choices_class: 'type[choices.Choices]',
        *,
        enum_type: str | None = None,
        **kwargs: typing.Any,
    ) -> None:
        if 'choices' in kwargs:
            raise TypeError(
                "EnumField() 'choices' is derived from choices_class and "
                "cannot be overridden; got an explicit 'choices' keyword too"
            )
        self.choices_class = choices_class
        self.enum_type = enum_type or _default_enum_type(choices_class)
        kwargs['choices'] = _choice_pairs(choices_class)
        if 'max_length' not in kwargs:
            kwargs['max_length'] = _max_length(choices_class)
        super().__init__(**kwargs)

    def db_type(self, connection: 'BaseDatabaseWrapper') -> str | None:
        # pragma: no cover below -- only reachable against a real Postgres
        # connection; exercised by `tox -e py313-django52-postgres`, never
        # by the sqlite-only default test run.
        if connection.vendor == 'postgresql':  # pragma: no cover
            return connection.ops.quote_name(self.enum_type)
        return super().db_type(connection)

    def deconstruct(
        self,
    ) -> 'tuple[str, str, Sequence[typing.Any], dict[str, typing.Any]]':
        name, path, _args, kwargs = super().deconstruct()
        # `choices` is always derived, never a real override -- carrying it
        # here would fight `choices_class` on every migration diff.
        del kwargs['choices']
        if kwargs.get('max_length') == _max_length(self.choices_class):
            del kwargs['max_length']
        if self.enum_type == _default_enum_type(self.choices_class):
            kwargs.pop('enum_type', None)
        else:
            kwargs['enum_type'] = self.enum_type
        return name, path, [self.choices_class], kwargs


class CreateEnumType(Operation):
    """Create a PostgreSQL ENUM type. Add to a migration BY HAND, before
    the operation that adds a column using it -- see the module docstring.
    """

    def __init__(self, name: str, values: 'Sequence[str]') -> None:
        self.name = name
        self.values = list(values)

    def state_forwards(self, app_label: str, state: 'ProjectState') -> None:
        pass

    def database_forwards(
        self,
        app_label: str,
        schema_editor: 'BaseDatabaseSchemaEditor',
        from_state: 'ProjectState',
        to_state: 'ProjectState',
    ) -> None:
        if schema_editor.connection.vendor != 'postgresql':
            return
        labels = ', '.join(  # pragma: no cover -- postgres tox env only
            schema_editor.quote_value(value) for value in self.values
        )
        schema_editor.execute(  # pragma: no cover -- postgres tox env only
            f'CREATE TYPE {schema_editor.quote_name(self.name)} '
            f'AS ENUM ({labels})'
        )

    def database_backwards(
        self,
        app_label: str,
        schema_editor: 'BaseDatabaseSchemaEditor',
        from_state: 'ProjectState',
        to_state: 'ProjectState',
    ) -> None:
        if schema_editor.connection.vendor != 'postgresql':
            return
        schema_editor.execute(  # pragma: no cover -- postgres tox env only
            f'DROP TYPE {schema_editor.quote_name(self.name)}'
        )

    def describe(self) -> str:
        return (
            f'Create PostgreSQL ENUM type {self.name!r} {tuple(self.values)}'
        )


class DropEnumType(Operation):
    """Drop a PostgreSQL ENUM type. The reverse of ``CreateEnumType`` --
    takes the same ``values`` so reversing THIS operation (recreating the
    type) has something to recreate.
    """

    def __init__(self, name: str, values: 'Sequence[str]') -> None:
        self.name = name
        self.values = list(values)

    def state_forwards(self, app_label: str, state: 'ProjectState') -> None:
        pass

    def database_forwards(
        self,
        app_label: str,
        schema_editor: 'BaseDatabaseSchemaEditor',
        from_state: 'ProjectState',
        to_state: 'ProjectState',
    ) -> None:
        if schema_editor.connection.vendor != 'postgresql':
            return
        schema_editor.execute(  # pragma: no cover -- postgres tox env only
            f'DROP TYPE {schema_editor.quote_name(self.name)}'
        )

    def database_backwards(
        self,
        app_label: str,
        schema_editor: 'BaseDatabaseSchemaEditor',
        from_state: 'ProjectState',
        to_state: 'ProjectState',
    ) -> None:
        if schema_editor.connection.vendor != 'postgresql':
            return
        labels = ', '.join(  # pragma: no cover -- postgres tox env only
            schema_editor.quote_value(value) for value in self.values
        )
        schema_editor.execute(  # pragma: no cover -- postgres tox env only
            f'CREATE TYPE {schema_editor.quote_name(self.name)} '
            f'AS ENUM ({labels})'
        )

    def describe(self) -> str:
        return f'Drop PostgreSQL ENUM type {self.name!r}'


class AddEnumValue(Operation):
    """Add a value to an existing PostgreSQL ENUM type, by hand, in its
    own migration entry -- see the module docstring for why this is
    ``atomic = False`` and irreversible.

    ``atomic = False`` on THIS operation is necessary but not sufficient:
    Django's migration executor opens its schema editor -- and with it,
    the wrapping transaction -- keyed on the *Migration's* ``atomic``
    attribute (default ``True``), before any operation's own ``atomic``
    flag is consulted. Put this operation in its own migration with
    ``atomic = False`` set as a CLASS attribute on that ``Migration``
    (same convention as Django's own ``AddIndexConcurrently``). Without
    that, ``database_forwards`` raises ``NotSupportedError`` rather than
    running inside a transaction it cannot safely run inside.
    """

    atomic = False

    def __init__(self, name: str, value: str) -> None:
        self.name = name
        self.value = value

    def state_forwards(self, app_label: str, state: 'ProjectState') -> None:
        pass

    def database_forwards(
        self,
        app_label: str,
        schema_editor: 'BaseDatabaseSchemaEditor',
        from_state: 'ProjectState',
        to_state: 'ProjectState',
    ) -> None:
        if schema_editor.connection.vendor != 'postgresql':
            return
        if schema_editor.connection.in_atomic_block:  # pragma: no cover
            # -- postgres tox env only; unreachable behind the vendor
            # guard above on every non-Postgres run.
            raise NotSupportedError(
                'AddEnumValue cannot run inside a transaction. Set '
                "'atomic = False' on the Migration class (the "
                'operation-level atomic attribute alone cannot escape '
                'an already-open migration transaction).'
            )
        schema_editor.execute(  # pragma: no cover -- postgres tox env only
            f'ALTER TYPE {schema_editor.quote_name(self.name)} '
            f'ADD VALUE IF NOT EXISTS {schema_editor.quote_value(self.value)}'
        )

    def database_backwards(
        self,
        app_label: str,
        schema_editor: 'BaseDatabaseSchemaEditor',
        from_state: 'ProjectState',
        to_state: 'ProjectState',
    ) -> None:
        raise IrreversibleError(
            'AddEnumValue cannot be reversed: PostgreSQL has no '
            'DROP VALUE. Recreate the type instead (CreateEnumType with '
            'the reduced value list under a new name, migrate the '
            'column and data across, DropEnumType the old one) -- see '
            'the README for the full recipe.'
        )

    def describe(self) -> str:
        return (
            f'Add value {self.value!r} to PostgreSQL ENUM type {self.name!r}'
        )
