sudo: false
language: python
python: 2.7

cache: pip

env:
    - TOX_ENV=coveralls
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django110
    - TOX_ENV=py35-django18
    - TOX_ENV=py35-django19
    - TOX_ENV=py35-django110
    - TOX_ENV=py36-django18
    - TOX_ENV=py36-django19
    - TOX_ENV=py36-django110
    - TOX_ENV=pypy-django18
    - TOX_ENV=pypy-django19
    - TOX_ENV=pypy-django110

install:
    - pip install --upgrade pip
    - pip install tox

script:
    tox -e $TOX_ENV

