language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r tests/requirements.txt --use-mirrors
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls

